### PR TITLE
Added fns to interact with the RTM API

### PR DESCRIPTION
**Pull request by casidiablo**

### CODE REVIEW

**Comment by julienXX** [comment]
That's really a cool feature but I have mixed feelings regarding all the dependencies it brings for the user. I'm not really sure it belongs to the lib or if it should be a separate project based on the lib because we make some choice regarding the web socket lib and so on that might cause headaches for others. What's your take on that?

**Comment by casidiablo** [comment]
I feel the same. I started small but as I advanced it started to grow bigger.

Does lein support `optional` dependencies like maven?

**Comment by casidiablo** [comment]
It looks like it's not possible. I will pull this out to its own project. For now I'll do it under my handle but we might as well create a github group to have both projects.

**Comment by julienXX** [comment]
Creating an org sounds good.

**Pull request closed without merging**
