### PR TITLE
Replace attachments with blocks

### PR DESCRIPTION
**Pull request by devth**
Fix https://github.com/julienXX/clj-slack/issues/55

I tested this locally and verified it works with [Yetibot](https://github.com/yetibot/yetibot)!

### CODE REVIEW

**Comment by devth** [comment]
Actually [they aren't deprecated](https://api.slack.com/messaging/composing/layouts#when-to-use-attachments) officially but we might want to drop them anyway?

**Comment by julienXX** [comment]
@devth thanks for this PR! Since attachments are still available I would prefer blocks support to be in another namespace and file if you don't mind.

**Comment by devth** [comment]
Why not keep them together alongside each other? They're both part of the `post-message` function.

**Comment by julienXX** [comment]
Hmm yes but I’m not sure Slack API would accept both attachments and blocks at the same time so that should be handled I guess.

**Comment by devth** [comment]
I will verify that.

**Comment by devth** [comment]
Verified. The top image is a Block and the `pretext` and below are part of the attachments:

image

Latest commit 1a0c6436 supports both.

**Comment by julienXX** [comment]
Thanks a lot!

**Comment by devth** [comment]
Mind cutting a release with this?

**Comment by julienXX** [comment]
Sure, I planned on doing one tomorrow :)

**Comment by devth** [comment]
Awesome thanks!

**Comment by julienXX** [comment]
0.6.3 has been pushed to clojars.

**Pull request merged**
