### PR TITLE
Fix warning related to the shadowing clojure.core/update

### PR DESCRIPTION
**Pull request by Gonzih**
Hi, here is small fix for the newer clojure versions.

### CODE REVIEW

**Comment by julienXX** [comment]
Thanks! Would you mind making the change for users and uaergroups as well?

**Comment by Gonzih** [comment]
Done!

**Comment by julienXX** [comment]
Thank you :)

**Comment by Gonzih** [comment]
No problem, any plans to release this change?

**Comment by julienXX** [comment]
Sure, just released v0.5.3 on Clojars.

**Comment by Gonzih** [comment]
Thanks!

**Pull request merged**
