### PR TITLE
Made post-message receive extra data

### PR DESCRIPTION
**Pull request by casidiablo**
Some context:

I'm writing a bot that will message members; `postMessage` [has a few optional arguments](https://api.slack.com/methods/chat.postMessage) that I'll need to customize. So now I can do things like:

```clojure
(slack-chat/post-message conn channel-id "some message"
      :username "my bot name"
      :icon_url "http://some.com/image.png")
```

This change is backwards compatible and can also be generalized for other API calls.

### CODE REVIEW

**Comment by julienXX** [comment]
That's my plan to add something like this all optional params but I'd also like to clean invalid params before sending them to Slack API. Not really sure on how I'll implement that but your proposal is a nice start.

**Comment by julienXX** [comment]
Perhaps it would be better to update your PR and put the parse-extras function in core.clj, that'll save me a commit ;)

**Comment by julienXX** [comment]
Wouldn't it be better to pass a map directly for optional args? I feel it can be weird to pass a sequence of keys and values after having the required args being simply values.

**Comment by casidiablo** [comment]
Sure that works for me too. It could also make it more clear that those are optional. I will update my PR

**Comment by casidiablo** [comment]
Done. So instead of using `[& extras]` I changed the function arity.

**Comment by julienXX** [comment]
Nice thanks!

**Comment by julienXX** [comment]
FYI I updated all the endpoints that can accept optional params in 0.4.0. Thanks again for your help :)

**Pull request merged**
